
obj-m:=pchar.o

all:
	make -C /home/Desktop/ELDD_260244230014/$(shell uname -r)/build M=$(shell pwd) modules

clean:
	make -C /home/Desktop/ELDD_260244230014/$(shell uname -r)/build M=$(shell pwd) clean

.PHONY: all clean